feat: use tencent cdn for cn user
Sekai-World/sekai-viewer pull request #295
Opened 2020-12-13 17:58 UTC by dnaroma

## Description

Loading data from github.io is very slow for users in China Mainland. Thus data is now replicated on Tencent Cloud, and if a user is physically in China Mainland and doesn't use a VPN, the requests for game data should be redirected to Tencent Cloud CDN.

## Motivation and Context

To speedup the connection for users in China Mainland, let them be able to access my site.

2020-12-14 08:00 UTC, xfl03 commented
## Issue
### Locale file is not loaded.
![1](https://user-images.githubusercontent.com/3205159/102055086-4529a000-3e25-11eb-9db4-bf8f3333a085.jpg)
### Master data is still loaded in GitHub Page.
![2](https://user-images.githubusercontent.com/3205159/102055104-4955bd80-3e25-11eb-86dd-97127dea6bd1.jpg)

2020-12-14 08:01 UTC, xfl03 requested changes
## Issue
### Locale file is not loaded.
![1](https://user-images.githubusercontent.com/3205159/102055086-4529a000-3e25-11eb-9db4-bf8f3333a085.jpg)
### Master data is still loaded in GitHub Page.
![2](https://user-images.githubusercontent.com/3205159/102055104-4955bd80-3e25-11eb-86dd-97127dea6bd1.jpg)

2020-12-14 10:59 UTC, dnaroma commented
locales file also needs to be uploaded to tencent cloud and load from there.

2020-12-20 14:33 UTC, xfl03 approved these changes

2020-12-20 14:33 UTC, merged