Adding Future Gachas/Future Events to a new tab for EN, KR, and TW ease of access
Sekai-World/sekai-viewer pull request #512
Opened 2024-07-29 17:46 UTC by Icequeen3333

## Description
Creating two new pages, one called Future Gacha, one called Future Event. These show events and gachas, starting from one year ago today on JP, in ascending order, only if spoiler tag is enabled. If the tag is not, it will show events on jp from ascending order (I didn't know what to do in this case, if any maintainer would have any other preferences as to what it should start at, I'd be willing to edit it.)

## Related Issue
[Adding Future Gacha/Future Event](https://github.com/Sekai-World/sekai-viewer/issues/505)

## Motivation and Context
Ease of access, we're three years into this game at this point, scrolling through all of the gachas and events to find out when a lim is getting reran or when an event you've been saving for will come back is extremely tedious, this is simply for ease of access.

## How Has This Been Tested?

- [X] Chrome (Desktop)
- [X] Chrome (Mobile)
- [X] Firefox (Desktop)
- [X] Firefox (Mobile)
- [ ] Safari (Desktop, optional)
- [ ] Safari (iPhone, optional)
- [ ] Safari (iPad, optional)

## Screenshots (if appropriate):
![image](https://github.com/user-attachments/assets/42f5f2f1-8073-426f-9c9a-fe4bb22508a9)

2024-07-29 19:47 UTC, Icequeen3333 commented
Still running some tests, so please don't merge it yet, theres something with futureevent that I'm trying to debug right now

2024-08-15 19:48 UTC, dnaroma requested changes
Still many small problems. For the folder structure, I would suggest rename folder `src/pages/futureevent` to `src/pages/future` since you put all future things in it.

2024-08-15 19:48 UTC, dnaroma commented on src/pages/App.tsx
> +        },
Prefer the future variants in a single menu item with children, I can do it after merge if you want

2024-08-15 19:48 UTC, dnaroma commented on package-lock.json
remove it

2024-08-15 19:48 UTC, dnaroma commented on src/pages/futureevent/FutureEventList.tsx
> +  function useCachedData<T extends IEventInfo>(
do not extend here, extend the function in `utils/index.ts`

2024-08-15 19:48 UTC, dnaroma commented on src/pages/futureevent/FutureEventList.tsx
> +    useRegion: ServerRegion = region
In React, `use` is considered as a reversed keyword for hooks

2024-08-15 19:48 UTC, dnaroma commented on src/pages/futureevent/FutureGachaList.tsx
> +  console.log("b");
remove `console.log`

2024-08-15 19:48 UTC, dnaroma commented on src/pages/futureevent/FutureEventList.tsx
> +        (e) => e.startAt >= new Date().getTime() - 31556952000
magic number? what is it?

2024-08-15 19:48 UTC, dnaroma commented on src/pages/futureevent/FutureEventList.tsx
> +    if (!isShowSpoiler) {
considering skip all the following steps and return empty array since this page shows "future events"

2024-08-15 19:48 UTC, dnaroma commented on src/pages/Home.tsx
> +            <Grid item>
Hide if `!isShowSpoiler`?

2024-08-15 19:48 UTC, dnaroma commented on src/pages/Home.tsx
> +            <Grid item>
Hide if `!isShowSpoiler`?

2024-08-15 19:48 UTC, dnaroma commented on src/pages/App.tsx
> +        {
Hide if `!isShowSpoiler`?

2024-08-15 19:48 UTC, dnaroma commented on src/pages/App.tsx
> +        {
Hide if `!isShowSpoiler`?

2024-08-15 19:48 UTC, dnaroma commented on src/pages/App.tsx
> +        },
Prefer the future variants in a single menu item with children, I can do it after merge if you want

2024-08-15 19:48 UTC, dnaroma commented on src/pages/futureevent/FutureEventList.tsx
> +    // eslint-disable-next-line react-hooks/exhaustive-deps
removed and it is fine for me

2024-08-15 19:48 UTC, dnaroma commented on src/pages/futureevent/FutureGachaGridView.tsx
> +    <Link to={"gacha/" + data.id} style={{ textDecoration: "none" }}>
`Link` won't work well because most of the future gachas exist only in JP

2024-08-15 19:48 UTC, dnaroma commented on src/pages/futureevent/FutureGachaGridView.tsx
> +    <Link to={"gacha/" + data.id} style={{ textDecoration: "none" }}>
I will consider add region to `path` params, or can be forced as a query param

2024-08-17 14:36 UTC, Icequeen3333 commented on src/pages/futureevent/FutureEventList.tsx
> +        (e) => e.startAt >= new Date().getTime() - 31556952000
Oh, I think I explained it in a past push and then deleted it, its a year worth of milliseconds

2024-08-17 14:40 UTC, Icequeen3333 commented on src/pages/futureevent/FutureEventList.tsx
> +    if (!isShowSpoiler) {
By this you mean setting sorted cache to just being an empty array and then breaking?

2024-08-17 14:41 UTC, Icequeen3333 commented on src/pages/futureevent/FutureGachaGridView.tsx
> +    <Link to={"gacha/" + data.id} style={{ textDecoration: "none" }}>
Alrighty, I saw that problem with the events when I was testing, I could try and make a futureGacha page as well where it gets the jp events with similar logic to the other functions?

2024-08-17 19:14 UTC, dnaroma commented on src/pages/futureevent/FutureGachaGridView.tsx
> +    <Link to={"gacha/" + data.id} style={{ textDecoration: "none" }}>
> Alrighty, I saw that problem with the events when I was testing, I could try and make a futureGacha page as well where it gets the jp events with similar logic to the other functions?

That's not necessary

2024-08-17 19:18 UTC, dnaroma requested changes

2024-08-17 19:18 UTC, dnaroma commented on src/pages/futureevent/FutureEventList.tsx
> +        (e) => e.startAt >= new Date().getTime() - 31556952000
> Oh, I think I explained it in a past push and then deleted it, its a year worth of milliseconds

It would be better to compare against the latest running event/gacha

2024-08-17 19:18 UTC, dnaroma commented on src/pages/futureevent/FutureEventList.tsx
> +    if (!isShowSpoiler) {
if `isShowSpoiler` is `false`, it means no spoiler should be shown, so it is meaningless to have `if (!isShowSpoiler)` branch here, or I misunderstood it

2024-08-29 22:22 UTC, Icequeen3333 commented on src/pages/futureevent/FutureEventList.tsx
> +        (e) => e.startAt >= new Date().getTime() - 31556952000
Sorry for the very late reply, just got back, do you mean sorting it by the event numbers, and only showing the ones after the current EN gacha number?

2024-12-30 14:27 UTC, closed without merging