feat: reimplement live2d story reader
Sekai-World/sekai-viewer pull request #529
Opened 2024-11-26 18:44 UTC by K-bai

## Description
Totally re-implemented live2d story reader for current version of sekai.best. No any dependency changes.

## Related Issue
#369 

## Motivation and Context
I NEED MORE CARD STORIES FOR MAFUYU!!!

## How Has This Been Tested?

- [x] Chrome (Desktop)
- [x] Chrome (Mobile)
- [x] Firefox (Desktop)
- [x] Firefox (Mobile)
- [ ] Safari (Desktop, optional)
- [ ] Safari (iPhone, optional)
- [ ] Safari (iPad, optional)

## Screenshots (if appropriate):
![image](https://github.com/user-attachments/assets/4e608132-196d-4b64-bd17-276efedc157f)

## features
- support basic scenario (talk, bgm, live2d motions)
- all necessary resource preloaded
- responsive layout and full screen support

## TODO

- NOT IMPLEMENT YET:
 - SnippetAction.InputName
 - SnippetAction.Selectable
 - SnippetAction.CharacerLayout <- typo in types.d
    - character moving
 - SnippetAction.SpecialEffect
    - SpecialEffectType.ShakeScreen
    - SpecialEffectType.ShakeWindow
    - SpecialEffectType.ChangeCardStill
    - SpecialEffectType.AmbientColorNormal
    - SpecialEffectType.AmbientColorEvening
    - SpecialEffectType.AmbientColorNight
    - SpecialEffectType.PlayScenarioEffect
    - SpecialEffectType.StopScenarioEffect
    - SpecialEffectType.ChangeBackgroundStill
    - SpecialEffectType.PlaceInfo
    - SpecialEffectType.Movie
    - SpecialEffectType.SekaiIn
    - SpecialEffectType.SekaiOut
    - SpecialEffectType.AttachCharacterShader
    - SpecialEffectType.SimpleSelectable
    - SpecialEffectType.FullScreenText
    - SpecialEffectType.StopShakeScreen
    - SpecialEffectType.StopShakeWindow
- bgm fade in and out
- expression conflict with motion (expressions are actually motion files, and pixi-live2d-display doesn't support two motions play simultaneously.)
- live2d lipsync (find a fork of pixi-live2d-display support this, but not tested yet)

2024-12-03 19:16 UTC, dnaroma commented
pixi-live2d-display is really limited, will consider replacing it

2024-12-03 20:51 UTC, dnaroma commented
Thank you for this PR! It looks pretty good and works well.

I did some simple tests and found some points to improve:
1. Event stories will load SE named like "se_event_xxx_xxx_001", this should be found under "event_story/event_xxx_xxx/scenario_se_rip". Current state: failed to load this file and it stucks. Code example:
```typescript
            const identifer = soundData.Se;
            const isEventSe = soundData.Se.startsWith("se_event");
            const baseDir = isEventSe
              ? `event_story/${soundData.Se.split("_").slice(1, -1).join("_")}`
              : "sound/scenario/se";
            const seBundleName = soundData.Se.startsWith("se_event")
              ? "scenario_se"
              : soundData.Se.endsWith("_b")
                ? "se_pack00001_b"
                : "se_pack00001";
            const url = `${baseDir}/${seBundleName}_rip/${soundData.Se}.mp3`;
```
2. Unload everything when user leaves the page. Current state: BGM and SE continues after leave.
3. You can play expression and motion one by one to avoid conflict.
4. Stop last voice/se if user clicked and a new one is played/triggered. Current state: voice line keeps playing even user clicked for the next one.
5. No motion loop. Current state: motion loops and it looks weird.

I'd like to merge it for an alpha version if you can fix some of them, especially the first one.

2024-12-03 20:54 UTC, dnaroma requested changes

2024-12-03 20:54 UTC, dnaroma commented on src/pages/App.tsx
> +              to: "/storyreader_live2d",
keep url kebab-case

2024-12-03 20:54 UTC, dnaroma commented on src/pages/App.tsx
> +              to: "/storyreader_live2d",
keep url kebab-case

2024-12-03 20:54 UTC, dnaroma commented on src/pages/App.tsx
> +              <Route path="/storyreader_live2d">
keep url kebab-case

2024-12-03 20:54 UTC, dnaroma commented on src/pages/App.tsx
> +              <Route path="/storyreader_live2d">
keep url kebab-case

2024-12-03 20:54 UTC, dnaroma commented on src/pages/storyreader-live2d/StoryReaderLive2DCanvas.tsx
> +// pixi-react nolonger supports pixi6.5, maybe this is the reason?
do we need to update pixi-react?

2024-12-03 20:54 UTC, dnaroma commented on src/utils/storyReaderLive2D/controller.ts
> +    console.log(this.app.stage.getChildByName("live2d"));
clean up console.log

2024-12-06 06:40 UTC, K-bai commented on src/pages/storyreader-live2d/StoryReaderLive2DCanvas.tsx
> +// pixi-react nolonger supports pixi6.5, maybe this is the reason?
Sorry it's been 2 days...It's not necessary in the current version, but if the lipsync and parallel motion playing is to be realized, it needs to be updated

There's a new version of pixi-live2d-display-lipsync@0.5.0(current 0.4.0) that depends on pixi@7 and have lipsync. And I just implemented multiple motions on pixi-live2d-display@0.5.0 but it's not merged yet.

I looked through all the codes and pixi/pixi-react/pixi-live2d-display are only used in live2d page and this pull request. No major changes in those libs. The update work is relative simple.

2024-12-06 06:48 UTC, K-bai commented
> Thank you for this PR! It looks pretty good and works well.
> 
> I did some simple tests and found some points to improve:
> 
>     1. Event stories will load SE named like "se_event_xxx_xxx_001", this should be found under "event_story/event_xxx_xxx/scenario_se_rip". Current state: failed to load this file and it stucks. Code example:
> 
> 
> ```ts
>             const identifer = soundData.Se;
>             const isEventSe = soundData.Se.startsWith("se_event");
>             const baseDir = isEventSe
>               ? `event_story/${soundData.Se.split("_").slice(1, -1).join("_")}`
>               : "sound/scenario/se";
>             const seBundleName = soundData.Se.startsWith("se_event")
>               ? "scenario_se"
>               : soundData.Se.endsWith("_b")
>                 ? "se_pack00001_b"
>                 : "se_pack00001";
>             const url = `${baseDir}/${seBundleName}_rip/${soundData.Se}.mp3`;
> ```
> 
>     2. Unload everything when user leaves the page. Current state: BGM and SE continues after leave.
> 
>     3. You can play expression and motion one by one to avoid conflict.
> 
>     4. Stop last voice/se if user clicked and a new one is played/triggered. Current state: voice line keeps playing even user clicked for the next one.
> 
>     5. No motion loop. Current state: motion loops and it looks weird.
> 
> 
> I'd like to merge it for an alpha version if you can fix some of them, especially the first one.

1. ok
2. ok
3. That's the way it is in the current version, and causes the motion playback lag a bit
4. ok
5. ok

2024-12-25 09:50 UTC, K-bai commented
The majority of the effects have been implemented! Ready to be merged, and please review!

2024-12-29 07:22 UTC, LazytownSpo666 commented
> The majority of the effects have been implemented! Ready to be merged, and please review!

@dnaroma is currently unable to review at this time. He may be pursuing on other project. And i can't review yours as well.

2024-12-29 08:13 UTC, dnaroma commented
> The majority of the effects have been implemented! Ready to be merged, and please review!

Thanks, I will review it ASAP, probably after new year :)

2025-01-07 12:08 UTC, LazytownSpo666 commented
> > The majority of the effects have been implemented! Ready to be merged, and please review!
> 
> Thanks, I will review it ASAP, probably after new year :)

Still waiting...

2025-01-12 08:20 UTC, dnaroma commented
It looks good, but has still some small bugs. I will merge it and fix it myself.

2025-01-12 08:32 UTC, merged

2025-01-13 03:47 UTC, LazytownSpo666 commented
This issue is now merged, but the live2d option is greyed out.